version: "3"
services:
  flask:
    build: api
    ports: ['5000:5000']
    volumes:
      - ./api:/api
    env_file:
      - .env
      - ./api/.env
    links:
      - redis
    depends_on:
      - redis

  workers:
      image: workers
      build:
          context: .
          dockerfile: workers/Dockerfile
      volumes:
          - ./workers:/usr/src/workers
          - ./api:/api
      env_file:
          - .env
          - ./api/.env
      links:
          - redis
      depends_on:
          - redis

  redis:
    image: redis
    expose:
      - 6379
    command: ["sh", "-c", "redis-server --appendonly yes"]

  rq-dashboard:
      image: rq-dashboard
      build:
          context: .
          dockerfile: rq-dashboard/Dockerfile
      ports:
          - '9181:9181'
      expose:
          - "9181"
      links:
          - redis
      depends_on:
          - redis